### PR TITLE
TF-2782: Replaced .gitignore file

### PR DESCRIPTION
**Pull request by joeporembski**

### CODE REVIEW

**Review by PGlaubitzWork — APPROVED** [review]

**Review by michelle-avery — APPROVED** [review]

**Review by adamrr — APPROVED** [review]
We should ... look at removing this repo at the next minor version or so.

**Review by adamcalhoon — COMMENTED** [review]
*.swp, *.swo, *.bag, *.zip, and *~ removed. I assume those were there for a reason.

**Comment by aoblena1346** [comment]
> *.swp, *.swo, *.bag, *.zip, and *~ removed. I assume those were there for a reason.

Should I add those back?

**Comment by adamcalhoon** [comment]
I'm not 100% sure in this case. The `*~` option has been removed from a bunch of repo's .gitignores so it doesn't seem to me like anyone would be upset if it was left out of the .gitignore. `*.swp` and `*.swo` are vim backup files so I suspect they also could be left off the .gitignore list. The other two someone else is going to have to weigh in on.

**Comment by michelle-avery** [comment]
For what it's worth, the previous gitignore file was from the original repo we forked from.

**Comment by adamcalhoon** [comment]
And given that @adamrr indicated this repo is on its deathbed, perhaps it doesn't matter too much.

@joeporembski can make the final call I guess?

**Comment by joeporembski** [comment]
Actually, given @adamrr's comments, and the huge lack of anything meaningful going on with this fork. I don't see any value in updating this.

**Pull request closed without merging**
